apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  clientId: {{ .Values.credentials.clientId | b64enc | quote }}
  clientSecret: {{ .Values.credentials.clientSecret | b64enc | quote }}
  baseUrl: {{ .Values.credentials.baseUrl | b64enc | quote }}

