name: Trigger Helm Chart Release

on:
  release:
    types: [published]

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Send Repository Dispatch Event
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.HELM_TRIGGER_TOKEN }}" \
               -H "Accept: application/vnd.github.everest-preview+json" \
               https://api.github.com/repos/runai-professional-services/helm-charts/dispatches \
               -d '{"event_type": "trigger-helm-release"}'

